{
 "title": "Hadoop dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HDFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Used (GB)",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.CapacityUsedGB",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "Remaining (GB)",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.CapacityRemainingGB",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Live Data Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.NumLiveDataNodes",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Dead DN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.NumDeadDataNodes",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Log Warnning",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "app": "datanode",
     "metric": "jvm.JvmMetrics.LogWarn",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Volume Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "app": "datanode",
     "metric": "dfs.datanode.VolumeFailures",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "RPC Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "metric": "rpc.rpc.client.NumOpenConnections",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Log Error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "app": "datanode",
     "metric": "jvm.JvmMetrics.LogError",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Decommissioning DN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.NumDecommissioningDataNodes",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "app": "namenode",
     "metric": "dfs.FSNamesystem.Snapshots",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Log Fatal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "app": "datanode",
     "metric": "jvm.JvmMetrics.LogFatal",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  { "title": "Yarn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "aggregator": "max",
     "alias": "Max HeapMem",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.MemHeapMaxM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Used HeapMem",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.MemHeapUsedM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Committed HeapMem",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.MemHeapCommittedM",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Non Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "aggregator": "max",
     "alias": "Used NonHeapMem",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.MemNonHeapUsedM",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Committed NonHeapMem",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.MemNonHeapCommittedM",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Node Managers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "max",
     "alias": "ActiveNMs",
     "app": "resourcemanager",
     "metric": "yarn.ClusterMetrics.NumActiveNMs",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Unhealthy",
     "app": "resourcemanager",
     "metric": "yarn.ClusterMetrics.NumUnhealthyNMs",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Decommissioned",
     "app": "resourcemanager",
     "metric": "yarn.ClusterMetrics.NumDecommissionedNMs",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Decommissioning",
     "app": "resourcemanager",
     "metric": "yarn.ClusterMetrics.NumDecommissioningNMs",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Application",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "max",
     "alias": "Completed",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AppsCompleted",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Failed",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AppsFailed",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Killed",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AppsKilled",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Pending",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AppsPending",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Running",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AppsRunning",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Submited",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AppsSubmitted",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Vcore",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Used Vcore",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AllocatedVCores",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "Avaiable Vcore",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AvailableVCores",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "Used Memory",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AllocatedMB",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "sum",
     "alias": "Avaiable Memory",
     "app": "resourcemanager",
     "metric": "yarn.QueueMetrics.Queue=root.AvailableMB",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Logger",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "max",
     "alias": "Warning",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogWarn",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Error",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogError",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Fatal",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogFatal",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "aggregator": "max",
     "alias": "Info",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogInfo",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Warnning",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogWarn",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Error",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogError",
     "precision": "default",
     "transform": "none"
    },
    {
     "aggregator": "max",
     "alias": "Fatal",
     "app": "resourcemanager",
     "metric": "jvm.JvmMetrics.LogFatal",
     "precision": "default",
     "transform": "none"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"yarn\", filename=\"/var/log/hadoop-yarn/yarn/nm-audit.log\"} |= ``"
    }
   ]
  }
 ]
}