{
 "title": "Server Monitoring",
 "description": "Streamline and optimize important metrics with Node Exporter v0.16+. Contains: CPU memory Disk IO network temperature and other monitoring indicators. https://github.com/starsliao/Prometheus translated by Google :-) ",
 "tags": [
  "Prometheus",
  "node_exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   { "name": "node", "label": "Node", "query": { "query": "label_values(server_name)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "System runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{server_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Audit number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{server_name=\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Usage rate（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{server_name=\"$node\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{server_name=\"$node\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{server_name=\"$node\"} / node_memory_MemTotal_bytes{server_name=\"$node\"}))* 100"
    }
   ]
  },
  {
   "title": "Currently open file descriptor",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{server_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Root partition usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{server_name=\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {server_name=\"$node\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Maximum partition ($maxmount) usage",
   "type": "gauge",
   "description": "Get the largest partition by the variable maxmount.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{server_name=\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {server_name=\"$node\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{server_name=\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System average load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_1m"
    },
    {
     "expr": "node_load5{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_5m"
    },
    {
     "expr": "node_load15{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_15m"
    }
   ]
  },
  {
   "title": "Total disk space",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes {server_name=\"$node\",fstype=~\"ext4|xfs\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {server_name=\"$node\",fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{server_name=\"$node\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{server_name=\"$node\",fstype=~\"ext4|xfs\"})"
    },
    {}
   ]
  },
  {
   "title": "CPU usage, disk I/O operations per second (%)",
   "type": "graph",
   "description": "Node_disk_io_time_seconds_total:\nThe number of milliseconds the disk spends on input/output operations. This value is the accumulated value. (Milliseconds Spent Doing I/Os)\n\nIrate(node_disk_io_time_seconds_total[1m]):\nCalculate the rate per second: (last value - last previous value) / timestamp difference, that is: the percentage of time that the disk spends on I/O operations in 1 second.",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{server_name=\"$node\",mode=\"system\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{server_name=\"$node\",mode=\"user\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{server_name=\"$node\",mode=\"iowait\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_per second I/O operating %"
    }
   ]
  },
  {
   "title": "Memory information",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_Total memory"
    },
    {
     "expr": "node_memory_MemTotal_bytes{server_name=\"$node\"} - node_memory_MemAvailable_bytes{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_Available"
    }
   ]
  },
  {
   "title": "Disk read and write rate（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每Reads completed: Reads per second for each disk partition\n\nWrites completed: Write completions per second for each disk partition\n\nIO now The number of input/output requests being processed per second per disk partition个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "iops", "label": "read（-）/write（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk read and write capacity",
   "type": "graph",
   "description": "Read bytes The number of bits read per second per disk partition\nWritten bytes The number of bits written per second per disk partition",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "Bps", "label": "read（-）/write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Disk IO read and write time",
   "type": "graph",
   "description": "Read time ms The number of seconds per disk partition read operation\n\nWrite time ms The number of seconds per disk partition write operation\n\nIO time ms Number of seconds spent per disk partition input/output operation\n\nIO time weighted Weighted seconds spent per disk partition input/output operation",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s", "label": "read（-）/ write（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_read"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_{{device}}_write"
    }
   ]
  },
  {
   "title": "Storage Occupied",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{server_name=\"$node\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{server_name=\"$node\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bps", "label": "upload（-）/download（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{server_name=\"$node\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{server_name=\"$node\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out upload"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "graph",
   "description": "CurrEstab - number of TCP connections with current state of ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from the CLOSED state to the SYN-SENT state (within 1 minute)\n\nPassiveOpens - TCP average connections that have been converted from the LISTEN state to the SYN-RCVD state (within 1 minute)\n\nTCP_alloc - the number of TCP sockets that have been allocated (established, applied to sk_buff)\n\nTCP_inuse - the number of TCP sockets being used (listening)\n\nTCP_tw - number of TCP connections waiting to be closed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_ESTABLISHED"
    },
    {
     "expr": "node_sockstat_TCP_tw{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_ActiveOpens"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{server_name=\"$node\"}[1m])",
     "legendFormat": "{{instance}}_PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_TCP_inuse"
    }
   ]
  },
  {
   "title": "Hardware temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{server_name=\"$node\"}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  }
 ]
}